### ISSUE TITLE
firmware version 3.3.4_0007.0004 is released

### ISSUE THREAD

**Issue by niceboygithub** [Wh1terat/aQRootG3#1]
firmware version 3.3.4_0007.0004 is released, will aQRootG3 still work?

**Comment by Wh1terat** [comment]
Not listed as available for me (yet).

Can you capture check update request and provide URL for firmware please.

**Comment by niceboygithub** [comment]
https://cdn.aqara.com/cdn/opencloud-product/mainland/product-firmware/prd/lumi.camera.gwpagl01/20211216200913_lumi.camera.gwpagl01_AIOT_V3.3.4_0007.0004_20211216_28f9c3.bin

**Comment by Wh1terat** [comment]
From static analysis it _looks_ like it is safe to update.
nslookup sprintf bug is still there and S90app init script hasn't changed in anyway that should affect.

**Comment by Wh1terat** [comment]
Finally appeared as available update today, tested upgrade and from reset - both ok.

Updated table.
https://github.com/Wh1terat/aQRootG3/commit/0679601a4878d00824eba4ca32ed5c96e056396a

Closing.
