### ISSUE TITLE
Is there a way to reverse it? 

### ISSUE THREAD

**Issue by tjxism** [Wh1terat/aQRootG3#12]
I tried connecting it directly to HA, and found it lost its hub function (didn't read README carefully....). Doesn't really work for me as i mainly use HomeKit as the front end... Now I connect it back to HomeKit and found the camera function is broken after the root. 

Is there a way to reverse the root?

**Comment by Wh1terat** [comment]
I don't use homekit myself but others have reported issues with it not working once they've tried to integrate with HA. 

I see _no_ reason why the root itself should cause this but I cannot comment about any HA plugins that then leverage telnet access to provide HA functionality and if they cause this issue or not.

To revert simply reset the camera (10 quick button presses in succession) and re-join it to Aqara Home.
