### ISSUE TITLE
How to update G3 firmware in telnet

### ISSUE THREAD

**Issue by glaypeng78** [Wh1terat/aQRootG3#14]
Thanks for your nice work. I was successfully go through the step you provide and use [niceboygithub/AqaraGateway](https://github.com/niceboygithub/AqaraGateway) to make my G3 intergrate into Home Assistant. Recently my Aqara Home app shows that there's a update to 3.3.9_0011.0004 and I mentioned that it dose not able to turn on telnet and mqtt at this version anymore. However my G3 is in 3.3.2 version and is there any way to manually update from 3.3.2 to 3.3.4 with the stock firmware?

**Comment by glaypeng78** [comment]
I’m sorry about my wrong expression. I’m not plan to update to the latest version. I want to update to the stable version 3.3.4. However the Aqara Home app only allow to update to the laters version. So what I need is the method to update to specific version thru telnet. Do you know wether it’s possible or not. If yes, can you tell me how to do it? Thanks.

> [#13 (comment)](https://github.com/Wh1terat/aQRootG3/issues/13#issuecomment-1116097348)
> 
> You could try to update since you already have telnet enabled, but ymmv from the user above.

**Comment by amaisano** [comment]
I also want to update my firmware via telnet. I have a VERY old version (`3.3.2_0001.0004`) and I would like to update it to 3.3.4 WITHOUT breaking telnet... please advise.
