### ISSUE TITLE
Password

### ISSUE THREAD

**Issue by zigomatichub** [Wh1terat/aQRootG3#6]
Hello Wh1terat, 
There is the possibility to set the password after that process to secure a bit the telnet ?

**Comment by Wh1terat** [comment]
Sure, just set your desired password using ```passwd``` as normal and then remove the line ```passwd -d $USER``` from ```/data/scripts/post_init.sh```

Be aware this will break other tools such as https://github.com/niceboygithub/AqaraCamera or https://github.com/niceboygithub/AqaraGateway which expect no password to be set.
