### ISSUE TITLE
0.3版图像无反应

### ISSUE THREAD

**Issue by wuqiyu007** [Wh1terat/aQRootG3#8]
0.3版图像无反应，用0.1版生成的图像可以开启telnet,固件最新版3.3.4_0007.0004

**Comment by Wh1terat** [comment]
@wuqiyu007 

0.1 - 0.2 is just different payload.
0.2 - 0.3 is same payload but fixed cipher for !"# and utf8 encoding.

What characters are used in your ssid and password ?

**Comment by wuqiyu007** [comment]
ssid:LINKSY_kiwi_5g  password:纯数字1-9

**Comment by Wh1terat** [comment]
Hmm. All simple ascii.

If you screenshot your aqara setup qrcode (from Aqara Home) and upload to: https://gchq.github.io/CyberChef/#recipe=Parse_QR_Code(true)

and then repeat for the qrcode from this script.

Are x= and y= values the same between them?

**Comment by nijez** [comment]
I also encountered the same problem, through https://gchq.github.io/CyberChef/#recipe=Parse_QR_Code(true) comparison, the two values are the same

**Comment by wuqiyu007** [comment]
3个qrcode结果如下。X Y值一样的，我替换了一部分，开头不太相同。
Aqara app qrcode:b=lumivItdL6EH7Gux&d=aiot-coap.aqara.cn&x=V******C79+9Cm;&y=qjl******qp&l=zh


aQRootG3 v0.3 qrcode: b=#!/bin/sh\nfw_manager.sh -r\npasswd -d $USER\nfw_manager.sh -t -k&d=a;y=/data/scripts/post_init.sh;"fw_man"ager.sh -t -f;echo -e `agetprop persist.app.bind_key`>$y;tail -n2 $y|sh&x=V******C79+9Cm;&y=qjl******qp&l=en


aQRootG3 v0.1 qrcode: b=lumiLZc1dhEfPzMN&d=aiot-coap.aqara.cn;x="fw_""manager.sh";$x -t -k;$x -t -f;y=/data/scripts/post_init.sh;echo "$x -t -k" >> $y;chmod 555 $y&x=V******C79+9Cm;&y=qjl******qp&l=en

**Comment by nijez** [comment]
@wuqiyu007，你0.1的文件能分享下吗？77797492@qq.com，谢谢！

**Comment by nijez** [comment]
请问为什么我用0.2版生成的qrcode扫描也没有反应？

**Comment by Wh1terat** [comment]
Definitely nothing to do with the cipher function as the ssid/pwd are the same for you both.

It's confusing that this works for some people and not for others despite everyone being on the same version.

@nijez you can find 0.1 in revision history: https://github.com/nijez/aQRootG3/blob/8f7b29662d170f508d56db06b2c4362e9a694b8d/aQRootG3.py

**Comment by nijez** [comment]
我的G3固件版本是3.3.4_0007.0004，目前测试了0.3、0.2、0.1三个版本生成的二维码，扫描都没有任何提示。

**Comment by nijez** [comment]
方便录制一段时间发到youtube上吗？

**Comment by Wh1terat** [comment]
I have CN version G3 also running 3.3.4_0007.0004, have just reset my camera and tested again and still works :confused: 

Did you follow steps to reset camera first? (press button 10x times)

**Comment by nijez** [comment]
> 我有 CN 版本 G3 也运行 3.3.4_0007.0004，刚刚重置我的相机并再次测试，仍然有效😕
> 
> 您是否按照步骤先重置相机？（按下按钮 10 次）

有的，每次都是按10次，提醒恢复出厂设置，然后用生成的二维码扫描。三个版本生成的二维码都没有任何提示，用Aqara Home生成的二维码给他扫描就马上提示扫描成功，进入下一步。

**Comment by wuqiyu007** [comment]
> > 我有 CN 版本 G3 也运行 3.3.4_0007.0004，刚刚重置我的相机并再次测试，仍然有效😕
> > 您是否按照步骤先重置相机？（按下按钮 10 次）
> 
> 有的，每次都是按10次，提醒恢复出厂设置，然后用生成的二维码扫描。三个版本生成的二维码都没有任何提示，用Aqara Home生成的二维码给他扫描就马上提示扫描成功，进入下一步。
https://mp.weixin.qq.com/s/Z-PFxyP9aXu6TzDnvYmxJw  你可以看看我写的过程，我试过0.1版的也是没反应，我截图做了一个反相的操作，和官方的二维码更接近就可以了。你试试PS反相下。或者按照我的步骤排查一下

**Comment by wuqiyu007** [comment]
> @wuqiyu007在较新的有效负载中有更多数据 - 查看您的教程，由于您的终端设置，您似乎必须做很多额外的工作来清理 qrcode，可能会丢失一些数据。
> 
> 如果您将第三个可选参数传递给脚本，它将将该文件保存为 png。 例如`aQRootG3.py ssid password image.png`
> 
> 您可以尝试使用不同的大小/设置重新编码 QRCode： `https://gchq.github.io/CyberChef/#recipe=Parse_QR_Code(true)Generate_QR_Code('PNG',5,2,'High')`

我的png文件是空的。0字节。可能是我的python的程序问题

**Comment by nijez** [comment]
> > > 我有版本 G3 运行 3.3.3.3.0007.0007.CN_0004，仍然我重新开始的摄像头并再次测试，有效😕
> > > 你是否按照步骤先设置摄像头？（点击按钮10次）
> > 
> > 
> > 有的，每次都恢复 10 次，提醒按出厂设置，然后用生成的二维码扫描。三个版本生成的二维码都没有，用 Aqara Home 生成的二维码给他扫描
> > [https://mp.weixin.com/s/Z-PFxyxin.com/s/Z-PFxyxinmxJw](https://mp.weixin.qq.com/s/Z-PFxyP9aXu6TzDnvYmxJw)你我写的过程，截图可以成功看到  我PQ0.1版的也没有反应，我做了一个反相的操作，和官方的二维码更近就可以了。你试试PS反相下。或者按照我的步骤排一下

我直接用你链接里反相好的这个二维码扫码也没有反应，估计是我摄像头的问题吧

**Comment by Wh1terat** [comment]
@nijez 
I'm not sure why you are not having success 😢 
I just created this QRCode and tested on a reset camera using hotspot from iPhone, perhaps you can perform a similar test with a hot spot from your phone/laptop ?

If nothing else at least see if your camera recognises this - even without wireless network existing it should still acknowledge the QR code and give "connecting" message before failing.

SSID = AqaraTest
Password = qwerty12345

![AqaraTest](https://user-images.githubusercontent.com/1288525/154811772-b769d703-9133-460d-a711-698be713efab.png)

**Comment by Sol1in** [comment]
I have the same issue: none of the QR-codes (v0.1, v0.2, v0.3 and even the one you attached here) were accepted by G3 - it just ignore it... but x= and y= are the same in generated QR and native from Aqara Home.

Here is my native QR from Aqara Home:
![AqaraG3_SelfQR](https://user-images.githubusercontent.com/49779647/154913198-aa917078-f4a3-419c-9998-b6bc760deb61.jpg)

I used this command in terminal (MacOS) to generate QR:
`python3 aQRootG3.py SoltinNet5G viasoft1721 code.png`

Here is the result:
![code3](https://user-images.githubusercontent.com/49779647/154913425-85dbdbb1-39fe-43db-9afe-f25a47083e7d.png)

Firmware: 3.3.4_0007.0004 (CN version)

**Comment by Wh1terat** [comment]
@Sol1in 
This is with my CN camera running 3.3.4_0007.0004 and just reset using you above qr code:

https://user-images.githubusercontent.com/1288525/155010588-e06dfcf8-1160-4af2-938d-c72dac120ca9.MOV

*shrug* 

I'm sorry, I can't think of anything to suggest.

**Comment by Sol1in** [comment]
Hmmm... do you use your laptop screen to cast QR to Cam? Did you tested it using your phone? Maybe size of the screen somehow affecting detection?

**Comment by Wh1terat** [comment]
@Sol1in ah I think maybe you have solved this mystery 😃 

You are correct, it does not scan from my phone either.

**Comment by Sol1in** [comment]
Oh yea! Theory confirmed! I used my Mac with big QR-code and it was scanned successfully!

**Comment by Wh1terat** [comment]
@nijez @wuqiyu007 
Can you confirm how you were scanning QR code too?

**Comment by nijez** [comment]
> @nijez @wuqiyu007 Can you confirm how you were scanning QR code too?

"Due to the amount of data in the QRCode, it is no longer possible for the camera to read from a small screen (such as a phone)."
This conclusion is correct, I scan successfully from the PC.

**Comment by nijez** [comment]
After scanning the QR code on the PC, there is a prompt that the network failed to add "Chinese prompt", and then scan the QR code generated by Aqara home, there is no prompt, I tried to press the reset button of the camera one or more times, but it did not No beeps appear and nothing else happens.

**Comment by nijez** [comment]
After I powered off and restarted, I scanned the QR code generated by Aqara home and successfully opened telnet.

**Comment by Wh1terat** [comment]
@nijez 
That's great, thank you for confirming!
Happy to hear you have had success! :rocket: 

After you have scanned the QR Code from aQRootG3 and the camera has given the message that it cannot connect (expected), if not prompted then you hold the button for 10s until it gives a message telling you to open aqara home - but a reboot will cause the same as you have found :smiley:

**Comment by Wh1terat** [comment]
> I want to buy you a cup of coffee, where do I need to transfer money to you?

That's very kind offer :coffee: but it is not necessary, I am glad everything is working for you :smiley:

**Comment by wuqiyu007** [comment]
> 看来要在电脑上扫描，我好像就是这样操作的

**Comment by Wh1terat** [comment]
Glad it is working for everyone now 😃
