### ISSUE TITLE
SSID/Password parsing error

### ISSUE THREAD

**Issue by meneer-code** [Wh1terat/aQRootG3#9]
Hi there

Thanks for the code!

I'm however still not able to log in after scanning the code and reaching step 5:

```
telnet: connect to address IP: Connection refused
telnet: Unable to connect to remote host
```

My SSID name contains a space and _[2.4Ghz]_, and my password contains a _$_

I made my command the following:

`$python3 aQRootG3.py "Networkname [2.4GHz]" pas$word`

Am I doing something wrong?

**Comment by Wh1terat** [comment]
Use single quotes for both, but especially for password since it contains  ```$```
```python3 aQRootG3.py 'Networkname [2.4GHz]' 'pas$word'```

**Comment by meneer-code** [comment]
@Wh1terat thanks so much for your response and follow up. I'm just away from home this week, will let you know as soon as I get back!

**Comment by meneer-code** [comment]
I tried that and scanned the QR code. It took a while for it to fail (Step 3), then when I try Step 4, it doesn't scan the QR code from the app unless I press and hold the reset button for 10s to do a network reset.

When I do this and set the camera up, it still gives me Connection refused

**Comment by Wh1terat** [comment]
@meneer-code 
It sounds like perhaps it still wasn't able to connect to the WiFi still during this step.

Just to be sure, can you upload both your Aqara home QR code and the one generated by this script to https://gchq.github.io/CyberChef/#recipe=Parse_QR_Code(true) and ensure the x and y values match.
(These are the ciphered SSID and passphrase sections)

**Comment by meneer-code** [comment]
@Wh1terat how do I decode and test the ciphered text? Tried a bunch of tools online.

I even tried to use generic ssid and password like 'networkname' and 'password' but when I upload the QR code I'm just getting this:

`
b=#!/bin/sh\nfw_manager.sh -r\npasswd -d $USER\nfw_manager.sh -t -k&d=a;y=/data/scripts/post_init.sh;"fw_man"ager.sh -t -f;echo -e `agetprop persist.app.bind_key`>$y;tail -n2 $y|sh&x=4=.+3074A5=&y=2A//+30>&l=en
`

If I understand you correctly I must decode 4=.+3074A5= and 2A//+30> to test if it's  'networkname' and 'password' ?

![qr-test](https://user-images.githubusercontent.com/15004267/156162761-6e46546d-cff2-4a92-9f14-a9a5d766c0f3.png)

**Comment by Wh1terat** [comment]
@meneer-code 

You don't need to decode the ciphered values - just compare.

Screenshot the QR code that Aqara Home gives you (and that works) and upload this screenshot of the QR code to a site like https://gchq.github.io/CyberChef/#recipe=Parse_QR_Code(true) 

Do the same for the one you generate from this script and then compare that the x and y values match.

This is to ensure that the script is generating the same ciphered ssid and password that aqara home does for your details.

**Comment by meneer-code** [comment]
Ah ok now I get it @Wh1terat 

I think there is a problem with the space in my network, because in the generated QR code there is laterally a space instead of something that looks like `"s`

**Comment by Wh1terat** [comment]
When I try:
'Networkname [2.4GHz]' = ```T=.+3074A5="sGptn[Z(E```
'pas$word' = ```2A/~+30>'```

I don't see any spaces? 

Are you using latest version (0.3) of the script?

**Comment by Wh1terat** [comment]
Ah interesting. 
Looks like it's being replaced when it gets encoded by the qrcode library.

Ok - lets try to get you sorted whilst I look into this.

Decode your aqara home qr code and replace the x and y values in the string you get from decoding the qr code from this script with them and then convert back into a qr code using https://gchq.github.io/CyberChef/#recipe=Generate_QR_Code('PNG',8,4,'High')

**Comment by meneer-code** [comment]
Got it working! Thanks so much

**Comment by Wh1terat** [comment]
Excellent 😃 
I'll close for now but will continue to look into the issue.
